export const staffNavigationItems = [
  {
    title: "Dashboard",
    icon: "bi-house-door",
    route: "/dashboard",
    module: null,
  },
  {
    title: "Applications",
    icon: "bi-file-earmark-text",
    route: "/applications",
    module: "applications",
  },
  {
    title: "Admission",
    icon: "bi-clipboard-check",
    route: "/admission",
    module: "admissions",
  },
  {
    title: "Students",
    icon: "bi-mortarboard-fill",
    route: "/students",
    module: "students",
  },
  {
    title: "Academics",
    icon: "bi-mortarboard",
    route: "/academics",
    module: "academics",
  },
  {
    title: "Course Registrations",
    icon: "bi-journal-check",
    route: "/course-registrations",
    module: "courseRegistrations",
  },
  {
    title: "Result Grading",
    icon: "bi-clipboard-data",
    route: "/result-grading",
    module: "academicResults",
  },
  {
    title: "Exams",
    icon: "bi-file-text",
    route: "/exams",
    module: "exams",
  },
  {
    title: "Users",
    icon: "bi-people",
    route: "/users",
    module: "users",
  },
  {
    title: "Payments",
    icon: "bi-credit-card-2-front",
    route: "/payments",
    module: "payments",
  },
  {
    title: "Notifications",
    icon: "bi-bell",
    route: "/notifications",
    module: "notifications",
  },
  {
    title: "Enquiries",
    icon: "bi-inbox",
    route: "/enquiries",
    module: "enquiries",
  },
  {
    title: "ID Cards",
    icon: "bi-person-badge",
    route: "/id-cards",
    module: "idCards",
  },
  {
    title: "Utilities",
    icon: "bi-tools",
    route: "/utilities",
    module: "utilities",
  },
  {
    title: "Reports & Analytics",
    icon: "bi-graph-up",
    route: "/reports",
    module: "reports",
  },
  {
    title: "Settings",
    icon: "bi-gear",
    route: "/settings",
    module: "settings",
  },
];
