import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type StudentPaymentDocument = StudentPayment & Document;

export enum PaymentStatus {
    PENDING = 'pending',
    SUCCESSFUL = 'successful',
    FAILED = 'failed',
    CANCELLED = 'cancelled',
}

export enum PaymentMethod {
    PAYSTACK = 'paystack',
    MANUAL_TRANSFER = 'manual_transfer',
}

export enum PaymentChannel {
    CARD = 'card',
    BANK_TRANSFER = 'bank_transfer',
    USSD = 'ussd',
    QR = 'qr',
    MOBILE_MONEY = 'mobile_money',
    MANUAL_TRANSFER = 'manual_transfer',
}

@Schema({ timestamps: true })
export class StudentPayment {
    @Prop({ type: Types.ObjectId, ref: 'User', required: true })
    userId: Types.ObjectId;

    @Prop({ type: Types.ObjectId, ref: 'Application' })
    applicationId?: Types.ObjectId;

    @Prop({ type: Types.ObjectId, ref: 'AcademicSession' })
    academicSessionId?: Types.ObjectId;

    @Prop({ type: Types.ObjectId, ref: 'Payment', required: true })
    paymentId: Types.ObjectId;

    @Prop({ required: true })
    amount: number; // Payment amount in Naira

    @Prop({ required: true, unique: true })
    reference: string;

    @Prop()
    paidAt?: Date;

    @Prop({ enum: PaymentMethod, default: PaymentMethod.PAYSTACK })
    method?: PaymentMethod;

    @Prop({ enum: PaymentChannel })
    channel?: PaymentChannel;

    @Prop()
    fee?: number; // Transaction fee in Naira (converted from kobo)

    @Prop()
    gatewayId?: string;

    @Prop({ required: true, enum: PaymentStatus, default: PaymentStatus.PENDING })
    status: PaymentStatus;

    @Prop()
    remarks?: string;

    @Prop({ default: 0 })
    retryCount?: number;

    @Prop()
    receiptUrl?: string;

    @Prop()
    receiptKey?: string;

    @Prop()
    receiptOriginalName?: string;

    @Prop()
    receiptUploadedAt?: Date;

    @Prop({ type: Types.ObjectId, ref: 'PaymentDestinationAccount' })
    destinationAccountId?: Types.ObjectId;

    @Prop()
    destinationChannelType?: string;

    @Prop()
    destinationProviderType?: string;

    @Prop()
    destinationAccountName?: string;

    @Prop()
    destinationBankName?: string;

    @Prop()
    destinationAccountNumber?: string;

    @Prop()
    destinationPaystackSubaccountCode?: string;

    // Paystack specific fields
    @Prop()
    authorizationCode?: string;

    @Prop()
    accessCode?: string;

    @Prop({ type: Types.ObjectId, ref: 'User' })
    verifiedBy?: Types.ObjectId;

    @Prop()
    verifiedAt?: Date;

    @Prop({ type: Types.ObjectId, ref: 'User' })
    rejectedBy?: Types.ObjectId;

    @Prop()
    rejectedAt?: Date;

    @Prop()
    verificationRemarks?: string;

    // Timestamp fields (auto-generated by mongoose)
    createdAt?: Date;
    updatedAt?: Date;
}

export const StudentPaymentSchema = SchemaFactory.createForClass(StudentPayment);
