<script setup>
import LegalPage from "../components/LegalPage.vue";
const sections = [
  { id: "information", title: "Information we may collect", paragraphs: ["We collect information needed to provide admissions, student, payment and support services."], items: ["Names, email addresses, phone numbers and mailing details", "Application and admission information submitted through our portals", "Academic and student account information required for school operations", "Payment references, payment status and uploaded transfer receipts", "Messages sent through contact or support channels", "Basic technical information such as browser type and access logs"] },
  { id: "use", title: "How we use information", paragraphs: ["Information is used only for legitimate institutional and operational purposes."], items: ["Review admissions applications and communicate updates", "Support student services, records and academic operations", "Process online payments and review transfer submissions", "Respond to questions, complaints and accessibility requests", "Secure systems, investigate misuse and improve service quality", "Meet school policy, legal and audit obligations"] },
  { id: "analytics", title: "Website analytics", paragraphs: ["ALECONS may use privacy-focused website analytics to understand how the public website is used and improve its content and performance. Analytics is configured to respect browser Do Not Track settings and to exclude URL search parameters and private verification routes."], items: ["Anonymous page views and navigation paths", "General referrer, browser and device information", "Approximate country or region derived by the analytics provider", "Interactions such as application, portal, WhatsApp and contact actions", "No contact-form content, names, email addresses, phone numbers, applicant identifiers or verification tokens"] },
  { id: "sharing", title: "Sharing and storage", paragraphs: ["ALECONS does not sell personal information. Information may be shared with authorised school personnel, trusted operational providers, payment processors, or where required by law or school governance.", "Uploaded files and records may be stored using secure cloud infrastructure and internal systems for continuity, verification and record keeping."] },
  { id: "choices", title: "Your choices", paragraphs: ["You may contact us to correct inaccurate information, request help understanding how your data is used, or raise concerns about privacy and account security.", "Some records must be retained to support admissions decisions, financial verification, academic administration and legal compliance."] },
];
</script>
<template><LegalPage eyebrow="Legal" title="Privacy Policy" description="How ALECONS collects, uses and protects information across our website and portals." :sections="sections" /></template>
